services:
  # === Наше Go-приложение ===
  app:
    build:
      context: ../../backend # Путь к папке backend относительно этого файла
      dockerfile: Dockerfile
    container_name: securemesh_api
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    env_file:
      - ../../.env # Читаем .env из корня

  # === База данных ===
  postgres:
    image: postgres:16-alpine
    container_name: securemesh_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    # Внутренний порт 5432, внешний не обязателен для production, 
    # но можно оставить для удобства
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # === Redis ===
  redis:
    image: redis:7-alpine
    container_name: securemesh_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # === MinIO ===
  minio:
    image: minio/minio
    container_name: securemesh_minio
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

volumes:
  postgres_data:
  redis_data:
  minio_data:
